### ISSUE TITLE
Getting 400 error response (invalid grant) for oauth token 

### ISSUE THREAD

**Issue by jordanpwood** [Mendeley/mendeleykit#105]
Some of our users are seeing a problem where their Mendeley token is not being renewed when they go to add an article to Mendeley via MendeleyKit on iOS.  I am seeing a 400 response from the POST request made from `MenedelyOAuthTokenHelper.refreshTokenWithRefreshBlock()` on line 46 (a call to `oauthProvider.refreshTokenWithOAuthCredentials()`).  the error is:

```
{
    NSLocalizedDescription = "400 bad request (https://api.mendeley.com/oauth/token)";
    NSLocalizedFailureReason =     {
        error = "invalid_grant";
        "error_description" = "Invalid grant";
    };
}
```
I am able to reproduce this error with a token that one of my test devices has that has not been renewed for a long time.  We have found that if we discard the OAuth token and make the user login to Mendeley again, then this problem goes away.

Could you help me understand under what conditions we would get this error, or any other related errors?  Is this error a problem with Mendeley's OAuth system, or is it an expected error that we are likely to see once in a while?  Please note that we have only started noticing this problem in the last couple of weeks.  

Thanks for your help!

**Comment by Aaron-Tunney** [comment]
Hi Jordan,

Due to a security issue a few weeks ago, a lot of user sessions were invalidated. This was communicated out to third-party developers but apologises if the message didn't make it through to your team. If the user signs out and signs back in, the problem should go away. Invalidating user sessions shouldn't be a regular occurrence but may happen again in the future.

Let me know if you have any further questions or signing out doesn't work for the user.
