### ISSUE TITLE
WebKit exception in logs. 

### ISSUE THREAD

**Issue by flagman** [Mendeley/mendeleykit#22]
Just playing with MendeleyKitOSXExample. 
All goes right, but there is exception in logs

`*** WebKit discarded an uncaught an exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil`

OSX 10.10.2

**Comment by pweschmidt** [comment]
Hi there
thanks for reporting this. I have a few questions to clarify what's actually happening:
- you say, all goes well: does that mean the example app doesn't crash with this exception?
- does this happen when you log in?

I assume in the example app you are using your registered (registered on dev.mendeley.com) client ID, client secret, redirect URI?

Many thanks
Peter

**Comment by flagman** [comment]
Hi, 
1. Yes, this exception doesn't crash the app. And a list of articles returned like it should. 
2. It happens when I log in. 

I am using credentials registered on dev.mendeley.com.

And what redirect link is a best choice for standalone OS X Application? 
It seems that webview delegate intercepts redirect and  take code from params.

**Comment by pweschmidt** [comment]
Thanks for clarifying this.
As for the redirect URI: there is no best choice for this, you could use something like http://localhost:8080/auth 
The only requirement is that it is exactly what you entered on the dev.mendeley.com portal

The WebView delegate does indeed redirect/intercept the call. Basically what happens is this: you request to go to the login page using the client ID/secret/redirect URI. The server then returns a HTML page containing the authentication code that then allows the client to go to the login page.
This HTML page will be the one set up/registered in the dev.mendeley.com portal.

Hope this makes sense

**Comment by vtourraine** [comment]
I’m a bit late to the party, but I’ve managed to track down the bug causing the log reported in this Issue.

When the WebView delegate finds the authentication code, it sends an authentication request to its OAuth provider.

``` objc
[self.oauthProvider authenticateWithAuthenticationCode:code
                                       completionBlock:oAuthCompletionBlock];
```

https://github.com/Mendeley/mendeleykit/blob/master/MendeleyKit/MendeleyKitOSX/AppKit/MendeleyLoginWindowController.m#L138

---

This call leads to this one, on `MendeleyDefaultOAuthProvider ` (note the `Task:nil` parameter):

```
[self executeAuthenticationRequestWithTask:nil requestHeader:requestHeader requestBody:requestBody completionBlock:completionBlock];
```
https://github.com/Mendeley/mendeleykit/blob/master/MendeleyKit/MendeleyKit/Networking/Default%20OAuth%20Provider/MendeleyDefaultOAuthProvider.m#L256

---

But when the underlying network provider is configured with `MendeleyNSURLConnectionProvider`, this finally leads to this:

```
- (void)executeTastWithRequest:(MendeleyRequest *)request
                          task:(MendeleyTask *)task
               completionBlock:(MendeleyResponseCompletionBlock)completionBlock
{
    MendeleyNSURLRequestHelper *requestHelper = [[MendeleyNSURLRequestHelper alloc] initWithMendeleyRequest:request completionBlock:completionBlock];

    task.requestObject =  requestHelper;
    BOOL hasStarted = [requestHelper startRequest];
    if (hasStarted)
    {
        [self.tasks addObject:task];
    }
}
```

https://github.com/Mendeley/mendeleykit/blob/master/MendeleyKit/MendeleyKit/Networking/NSURLConnection%20Provider/MendeleyNSURLConnectionProvider.m#L504

As you can see with this last operation, the `task` parameter is added to the array, but having a `nil` value causes the exception (on OS X, exceptions don’t crash the app, it just logs a warning; on iOS, that would indeed crash).

So I think the problem is not specific to OS X, but to the `MendeleyNSURLConnectionProvider`, and how it works with the authentication flow. We can simply test for `task` not being `nil` before adding it to the array, but I’m wondering if it’s the right place to fix that. We might need to change it more upstream.

Also: nullability annotations with Xcode 6.3 would fix this problem. https://developer.apple.com/swift/blog/?id=25

**Comment by pweschmidt** [comment]
Hi Vincent, good catch. Let me look into that and see how we can fix this.
