### ISSUE TITLE
Authorization in Mendeley

### ISSUE THREAD

**Issue by ed8009** [Mendeley/mendeleykit#64]
Hello. Is there a way to make API requests without authorization on the new device? Is it always necessary to show the user login window? I registered and received my application clientId, ClientSecret and ClientRedirect

**Comment by pweschmidt** [comment]
Hi there. Not sure exactly what alternative ways of handling API requests you would like to implement. But all API calls made to the server require user login. You may store the authentication credentials in the local keychain to avoid the user from logging in each time they use the app. The SDK handles refresh of authentication tokens automatically.
But yes, authentication is required.

As for the login process. We follow an OAuth authentication path. Part of that is login via web, so that the device need not store username/password.

Hope this makes sense?
Best wishes
Peter

**Comment by ed8009** [comment]
Thank you for such a quick response. Yes, I totally agree with your opinion.
